spring:
  application:
    name: crbook-config
  cloud:
    config:
      server:
        git:
          timeout: 5
          uri:  https://github.com/LZP0517/spring-crbook.git
          username: LZP0517
          password: lizhipeng0517
          default-label: main
          search-paths: config

server:
  port: 8888



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
